defaults:
  for:
  - all
traits:
- id: deeply-nested-extconf-metadata
  desc: Deeply nested extconf.rb in metadata.yaml
  conf: 0.9
  crit: suspicious
  if:
    type: raw
    regex: extensions:\s*\n\s*-\s*ext/[^/]{1,120}/[^/]{1,120}/[^/]{1,120}/extconf\.rb
- id: deeply-nested-extconf-gemspec
  desc: Deeply nested extconf.rb in gemspec
  conf: 0.9
  crit: suspicious
  if:
    type: raw
    regex: extensions\s*<<\s*['"]ext/[^/]{1,120}/[^/]{1,120}/[^/]{1,120}/extconf\.rb['"]
- id: deeply-nested-extconf-gemspec-assign
  desc: Deeply nested extconf.rb in gemspec list
  conf: 0.9
  crit: suspicious
  if:
    type: raw
    regex: extensions\s*=\s*\[.{0,220}['"]ext/.{1,240}/extconf\.rb['"]
composite_rules: []
