# Configuration File Paths (Linux)
# MBC: E1083 (File and Directory Discovery)
# ATT&CK: T1083

traits:
  - id: config-etc
    description: Reference to /etc configuration files
    crit: inert
    conf: 0.66
    if:
      type: string
      regex: "/etc/[\\w\\.\\-/]{1,32}"

  - id: config-hosts
    description: Reference to /etc/hosts
    crit: notable
    conf: 0.66
    if:
      type: string
      exact: /etc/hosts

  - id: config-resolv
    description: Reference to /etc/resolv.conf
    crit: notable
    conf: 0.66
    if:
      type: string
      exact: /etc/resolv.conf

  - id: config-initd
    description: Reference to /etc/init.d scripts
    crit: notable
    conf: 0.66
    if:
      type: string
      regex: "/etc/init\\.d/[\\w\\-]+"
